### ISSUE TITLE
ImportError: dlopen(..._pycryptonight.cpython-38-darwin.so, 2): Symbol not found: _memwipe

### ISSUE THREAD

**Issue by czha168** [ph4r05/py-cryptonight#12]
Hi there,
Just installed on my Mac with pip, got this error by importing.
So I cloned the git and run "python setup.py test", same error. 
Is this Mac specific?
I am using Python 3.8.

**Comment by ph4r05** [comment]
there might be an error in the latest release, pls try 0.3.4

**Comment by czha168** [comment]
That fixed the problem.
Thank you.

**Comment by ph4r05** [comment]
You are welcome :)
