### ISSUE TITLE
Monero CNv4 Hard Fork

### ISSUE THREAD

**Issue by aaronllowe** [ph4r05/py-cryptonight#3]
Hello, 
I appreciate all of the work you put into this! I use it regularly for Python Monero mining, but the CNv4 or Cryptonight R hardfork is coming up and I wanted to know if you could update the code so I could mine again. Thank you for making this and best of luck!

**Comment by ph4r05** [comment]
Hi! Thanks for info. I am working on it right now

**Comment by ph4r05** [comment]
fixed in v0.2.0

**Comment by ph4r05** [comment]
v0.2.3

**Comment by aaronllowe** [comment]
Thanks!
