### ISSUE TITLE
Windows 10 round 2

### ISSUE THREAD

**Issue by XxAzeSxX** [ph4r05/py-cryptonight#6]
how to use  https://gist.github.com/mbikovitsky/39224cf521bfea7eabe9 ?

_Originally posted by @XxAzeSxX in https://github.com/ph4r05/py-cryptonight/issues/5#issuecomment-583857874_

**Comment by ph4r05** [comment]
I am happy to merge a pull request fixing this :)

**Comment by XxAzeSxX** [comment]
satisfied? ¯\_༼ ಥ ‿ ಥ ༽_/¯

**Comment by ph4r05** [comment]
Is there a PR already? :)

**Comment by XxAzeSxX** [comment]
Yes, had it ready, but im a github n00b, so i forgot to push it: https://github.com/ph4r05/py-cryptonight/pull/7 ^^
