### ISSUE TITLE
I can't install py-cryptonight

### ISSUE THREAD

**Issue by eeblocks** [ph4r05/py-cryptonight#9]
`pip install py-cryptonight                             `
                                    
Collecting py-cryptonight                                                                                                 Using cached py_cryptonight-0.3.3.tar.gz (352 kB)                                                                     Building wheels for collected packages: py-cryptonight                                                                    Building wheel for py-cryptonight (setup.py) ... error                                                                  ERROR: Command errored out with exit status 1:                                                                           command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k4cdqjd3                                                                          cwd: /tmp/pip-install-0gece5x4/py-cryptonight/                                                                     Complete output (36 lines):                                                                                             running bdist_wheel                                                                                                     running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build/lib.linux-x86_64-3.8                                                                                     creating build/lib.linux-x86_64-3.8/pycryptonight                                                                       copying pycryptonight/__init__.py -> build/lib.linux-x86_64-3.8/pycryptonight                                           creating build/lib.linux-x86_64-3.8/pycryptonight/tests                                                                 copying pycryptonight/tests/test.py -> build/lib.linux-x86_64-3.8/pycryptonight/tests                                   copying pycryptonight/tests/__init__.py -> build/lib.linux-x86_64-3.8/pycryptonight/tests                               running egg_info                                                                                                        writing py_cryptonight.egg-info/PKG-INFO                                                                                writing dependency_links to py_cryptonight.egg-info/dependency_links.txt                                                writing requirements to py_cryptonight.egg-info/requires.txt                                                            writing top-level names to py_cryptonight.egg-info/top_level.txt                                                        reading manifest file 'py_cryptonight.egg-info/SOURCES.txt'                                                             reading manifest template 'MANIFEST.in'                                                                                 writing manifest file 'py_cryptonight.egg-info/SOURCES.txt'                                                             creating build/lib.linux-x86_64-3.8/pycryptonight/tests/data                                                            copying pycryptonight/tests/data/tests-fast.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                  copying pycryptonight/tests/data/tests-slow-1.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow-2.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow-4.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                  running build_ext                                                                                                       building '_pycryptonight' extension                                                                                     creating build/temp.linux-x86_64-3.8                                                                                    creating build/temp.linux-x86_64-3.8/src                                                                                creating build/temp.linux-x86_64-3.8/src/cryptonight                                                                    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNO_JIT=1 -I. -Isrc/ -Isrc/cryptonight -I/usr/include/python3.8 -c src/cryptonight/aesb.c -o build/temp.linux-x86_64-3.8/src/cryptonight/aesb.o -std=gnu11 -maes                                                  In file included from src/cryptonight/aesb.c:21:                                                                        /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory                     9 | # include_next <stdint.h>                                                                                             |                ^~~~~~~~~~                                                                                       compilation terminated.                                                                                                 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                         ----------------------------------------                                                                                ERROR: Failed building wheel for py-cryptonight                                                                         Running setup.py clean for py-cryptonight                                                                             Failed to build py-cryptonight                                                                                          Installing collected packages: py-cryptonight                                                                               Running setup.py install for py-cryptonight ... error                                                                   ERROR: Command errored out with exit status 1:                                                                           command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7ntvygnk/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ezequiel/.local/include/python3.8/py-cryptonight                                    cwd: /tmp/pip-install-0gece5x4/py-cryptonight/                                                                     Complete output (36 lines):                                                                                             running install                                                                                                         running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build/lib.linux-x86_64-3.8                                                                                     creating build/lib.linux-x86_64-3.8/pycryptonight                                                                       copying pycryptonight/__init__.py -> build/lib.linux-x86_64-3.8/pycryptonight                                           creating build/lib.linux-x86_64-3.8/pycryptonight/tests                                                                 copying pycryptonight/tests/test.py -> build/lib.linux-x86_64-3.8/pycryptonight/tests                                   copying pycryptonight/tests/__init__.py -> build/lib.linux-x86_64-3.8/pycryptonight/tests                               running egg_info                                                                                                        writing py_cryptonight.egg-info/PKG-INFO                                                                                writing dependency_links to py_cryptonight.egg-info/dependency_links.txt                                                writing requirements to py_cryptonight.egg-info/requires.txt                                                            writing top-level names to py_cryptonight.egg-info/top_level.txt                                                        reading manifest file 'py_cryptonight.egg-info/SOURCES.txt'                                                             reading manifest template 'MANIFEST.in'                                                                                 writing manifest file 'py_cryptonight.egg-info/SOURCES.txt'                                                             creating build/lib.linux-x86_64-3.8/pycryptonight/tests/data                                                            copying pycryptonight/tests/data/tests-fast.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                  copying pycryptonight/tests/data/tests-slow-1.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow-2.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow-4.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                copying pycryptonight/tests/data/tests-slow.txt -> build/lib.linux-x86_64-3.8/pycryptonight/tests/data                  running build_ext                                                                                                       building '_pycryptonight' extension                                                                                     creating build/temp.linux-x86_64-3.8                                                                                    creating build/temp.linux-x86_64-3.8/src                                                                                creating build/temp.linux-x86_64-3.8/src/cryptonight                                                                    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNO_JIT=1 -I. -Isrc/ -Isrc/cryptonight -I/usr/include/python3.8 -c src/cryptonight/aesb.c -o build/temp.linux-x86_64-3.8/src/cryptonight/aesb.o -std=gnu11 -maes                                                  In file included from src/cryptonight/aesb.c:21:                                                                        /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory                     9 | # include_next <stdint.h>                                                                                             |                ^~~~~~~~~~                                                                                       compilation terminated.                                                                                                 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                         ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gece5x4/py-cryptonight/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7ntvygnk/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ezequiel/.local/include/python3.8/py-cryptonight Check the logs for full command output.

**Comment by krzycho2** [comment]
Same here. I tried installing on Ubuntu 16.04

**Comment by ph4r05** [comment]
pls try again with 0.3.5. Closing, reopen if problem still persists, thanks!
